//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_GAIntegrationWSTest_WA.InventoryGoods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryGoods.IInventory")]
    public interface IInventory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/SaveInventoryGoodsIssue", ReplyAction="http://tempuri.org/IInventory/SaveInventoryGoodsIssueResponse")]
        string SaveInventoryGoodsIssue(string jsonString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/SaveInventoryGoodsRecipet", ReplyAction="http://tempuri.org/IInventory/SaveInventoryGoodsRecipetResponse")]
        string SaveInventoryGoodsRecipet(string jsonString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventoryChannel : AE_GAIntegrationWSTest_WA.InventoryGoods.IInventory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryClient : System.ServiceModel.ClientBase<AE_GAIntegrationWSTest_WA.InventoryGoods.IInventory>, AE_GAIntegrationWSTest_WA.InventoryGoods.IInventory {
        
        public InventoryClient() {
        }
        
        public InventoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveInventoryGoodsIssue(string jsonString) {
            return base.Channel.SaveInventoryGoodsIssue(jsonString);
        }
        
        public string SaveInventoryGoodsRecipet(string jsonString) {
            return base.Channel.SaveInventoryGoodsRecipet(jsonString);
        }
    }
}
